<template><div class="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><section class="rounded-[2rem] border border-slate-200/80 bg-panel/75 p-5"><label class="text-sm font-semibold text-slate-950">搜索管理员任务<input v-model="keyword" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-ink-2 px-4 py-3 text-slate-900" /></label><div class="mt-5 space-y-3"><button v-for="job in filteredJobs" :key="job.id" type="button" class="w-full rounded-2xl border border-slate-200/80 bg-white/[0.03] p-4 text-left hover:border-gold/40" @click="selectedId = job.id"><div class="flex justify-between gap-4"><span class="font-bold text-slate-950">{{ job.title }}</span><span class="rounded-full px-2.5 py-1 text-xs font-bold" :style="{ color: getRiskMeta(job.riskLevel).color, background: getRiskMeta(job.riskLevel).backgroundColor }">{{ getRiskMeta(job.riskLevel).label }}</span></div><p class="mt-2 text-sm text-slate-500">用户：{{ job.ownerName }} · 任务 {{ job.id }}</p><p v-if="job.reviewStatus === 'pending'" class="mt-2 text-xs font-bold text-slate-700">待人工复核</p></button></div></section><aside class="rounded-[2rem] border border-gold/20 bg-gold/10 p-6"><h2 class="text-xl font-bold text-slate-950">任务详情</h2><div v-if="selectedJob" class="mt-5 space-y-3 text-sm text-slate-600"><p>任务ID：{{ selectedJob.id }}</p><p>用户：{{ selectedJob.ownerName }}</p><p>品牌：{{ selectedJob.brand }}</p><p>市场：{{ selectedJob.market }}</p><p>复核状态：{{ reviewLabels[selectedJob.reviewStatus ?? 'none'] }}</p><p v-if="selectedJob.reviewNote">复核备注：{{ selectedJob.reviewNote }}</p><img v-if="selectedJob.fileUrl" :src="assetUrl(selectedJob.fileUrl)" :alt="selectedJob.title" class="h-36 w-full rounded-2xl border border-gold/20 bg-ink-2 object-cover" /><div v-else class="grid h-36 place-items-center rounded-2xl border border-gold/20 bg-ink-2 text-slate-700">暂无原始文件</div><div class="rounded-2xl border border-slate-200/80 bg-ink-2 p-4"><label class="text-sm font-semibold text-slate-950">复核处理备注<textarea v-model="adminNote" rows="3" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-panel px-4 py-3 text-slate-900" placeholder="填写复核处理意见" /></label><div class="mt-3 flex flex-col gap-3 sm:flex-row"><button type="button" :disabled="submitting" class="rounded-full bg-gold px-5 py-3 text-sm font-bold text-white disabled:opacity-60" @click="handleReview('approved')">通过复核</button><button type="button" :disabled="submitting" class="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-slate-950 disabled:opacity-60" @click="handleReview('rejected')">驳回复核</button></div><p v-if="message" class="mt-3 text-sm text-slate-700">{{ message }}</p></div></div></aside></div></template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import { updateAdminJobReview } from '@/api/client'
import { getRiskMeta } from '@/utils/risk'
import type { DetectionJob, ReviewStatus } from '@/types/domain'
const props = defineProps<{ jobs: DetectionJob[] }>()
const localJobs = ref([...props.jobs])
const keyword = ref('')
const selectedId = ref(props.jobs[0]?.id ?? '')
const adminNote = ref('')
const message = ref('')
const submitting = ref(false)
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000'
const reviewLabels: Record<ReviewStatus, string> = { none: '未申请', pending: '待人工复核', approved: '已通过复核', rejected: '已驳回复核' }
const selectedJob = computed(() => localJobs.value.find((job) => job.id === selectedId.value) ?? localJobs.value[0])
const filteredJobs = computed(() => localJobs.value.filter((job) => `${job.ownerName} ${job.title} ${job.id}`.toLowerCase().includes(keyword.value.toLowerCase())))
function assetUrl(path: string) { return path.startsWith('http') ? path : `${API_BASE_URL}${path}` }
async function handleReview(status: 'approved' | 'rejected') { if (!selectedJob.value || submitting.value) return; submitting.value = true; message.value = ''; try { const updated = await updateAdminJobReview(selectedJob.value.id, status, adminNote.value); localJobs.value = localJobs.value.map((job) => job.id === updated.id ? updated : job); message.value = status === 'approved' ? '已通过复核' : '已驳回复核' } catch { message.value = '处理失败，请稍后重试' } finally { submitting.value = false } }
</script>
