<template><section class="rounded-[2rem] border border-slate-200/80 bg-panel/75 p-6"><div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[0.3em] text-slate-700">Model Settings</p><h2 class="mt-2 text-xl font-bold text-slate-950">大模型报告配置</h2></div><span class="text-sm text-slate-500">用于生成检测报告</span></div><div class="mt-6 grid gap-4 md:grid-cols-2"><label class="text-sm font-semibold text-slate-950">服务商<select v-model="form.provider" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-ink-2 px-4 py-3 text-slate-900"><option value="anthropic">anthropic</option><option value="openai">openai</option></select></label><label class="text-sm font-semibold text-slate-950">模型名称<input v-model="form.modelName" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-ink-2 px-4 py-3 text-slate-900" placeholder="gpt-4.1-mini" /></label><label class="text-sm font-semibold text-slate-950">Base URL<input v-model="form.baseUrl" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-ink-2 px-4 py-3 text-slate-900" :placeholder="baseUrlPlaceholder" /></label><label class="text-sm font-semibold text-slate-950">API Key<input v-model="form.apiKey" type="password" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-ink-2 px-4 py-3 text-slate-900" placeholder="保存时会覆盖旧 Key" /></label><label class="text-sm font-semibold text-slate-950">Temperature<input v-model.number="form.temperature" type="number" step="0.1" min="0" max="2" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-ink-2 px-4 py-3 text-slate-900" /></label><label class="text-sm font-semibold text-slate-950">Max Tokens<input v-model.number="form.maxTokens" type="number" min="512" max="8192" class="mt-2 w-full rounded-2xl border border-slate-200/80 bg-ink-2 px-4 py-3 text-slate-900" /></label></div><label class="mt-5 flex items-center gap-3 text-sm font-semibold text-slate-950"><input v-model="form.enabled" type="checkbox" class="h-4 w-4 accent-gold" />启用大模型生成报告</label><div class="mt-6 flex items-center gap-4"><button type="button" :disabled="saving" class="rounded-full bg-gold px-5 py-3 text-sm font-bold text-white disabled:opacity-60" @click="save">{{ saving ? '保存中' : '保存配置' }}</button><p v-if="message" class="text-sm text-slate-700">{{ message }}</p></div></section></template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { getModelConfig, updateModelConfig } from '@/api/client'
const form = reactive({ provider: 'anthropic', modelName: 'gpt-4.1-mini', apiKey: '', baseUrl: 'https://newapi.lxhei.xyz', temperature: 0.2, maxTokens: 2048, enabled: true })
const saving = ref(false)
const message = ref('')
const baseUrlPlaceholder = computed(() => form.provider === 'anthropic' ? 'https://newapi.lxhei.xyz' : 'https://api.openai.com/v1')
onMounted(async () => { const data = await getModelConfig(); if (data.config) Object.assign(form, { ...data.config, apiKey: '' }); if (String(form.baseUrl).includes('newapi')) form.provider = 'anthropic' })
async function save() { saving.value = true; message.value = ''; try { await updateModelConfig(form); message.value = '模型配置已保存' } catch { message.value = '保存失败，请检查配置' } finally { saving.value = false } }
</script>
